In [45]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
# List of CSV file names with full path
csv_files = [
    r"phantombuster-all-leads-08232025 (5).csv",
    r"phantombuster-all-leads-08232025 (4).csv",
    r"phantombuster-all-leads-08232025 (3).csv",
    r"phantombuster-all-leads-08232025 (2).csv",
    r"phantombuster-all-leads-08232025 (1).csv",
    r"phantombuster-all-leads-08232025.csv"
]

In [4]:
# Read and merge all CSV files
dataframes = [pd.read_csv(file) for file in csv_files]

In [5]:
# Concatenate into a single DataFrame
merged_df = pd.concat(dataframes, ignore_index=True)

In [6]:
# Save the merged CSV
output_file = r"E:\OneDrive\Desktop\Scraped Data - LinkedIn\merged_linkedin_data.csv"
merged_df.to_csv(output_file, index=False)

In [7]:
print(f"✅ Merged CSV saved at: {output_file}")

✅ Merged CSV saved at: E:\OneDrive\Desktop\Scraped Data - LinkedIn\merged_linkedin_data.csv

In [8]:
df = pd.read_csv("merged_linkedin_data.csv")

In [9]:
df.head()

,linkedinProfileUrl,salesNavigatorProfileUrl,fullName,firstName,lastName,companyName,personalWebsite,linkedinJobTitle,linkedinJobDateRange,linkedinJobLocation,...,salesNavigatorProfileSlug,linkedinProfileId,linkedinProfileUrn,linkedinIsHiringBadge,linkedinIsOpenToWorkBadge,id,createdAt,updatedAt,createdBy,updatedBy
0,https://linkedin.com/in/shoaib-khan-9b80b0205,https://www.linkedin.com/sales/lead/ACoAADQpUJ...,Shoaib Khan,Shoaib,Khan,ReConnectIn Technologies Pvt Ltd,sk2apps.com/,Senior Android Developer,Jan 2024 - Present,"Jodhpur, Rajasthan, India · Remote",...,ACoAADQpUJwBt5qJlE6Q10OaVG0nYYRWOJNGi0k,875122844.0,ACoAADQpUJwBt5qJlE6Q10OaVG0nYYRWOJNGi0k,No,Yes,2.087003e+15,8/23/2025,8/23/2025,Untitled LinkedIn Profile Visitor (1),Untitled LinkedIn Profile Visitor (1)
1,https://linkedin.com/in/arivazhahan-selva-8314...,https://www.linkedin.com/sales/lead/ACoAACKY42...,Arivazhahan Selva,Arivazhahan,Selva,Zolve,NaN,Data Analyst,Oct 2022 - Present,On-site,...,ACoAACKY42UB-5MF-Di8nhxzJnPKV5LPrdLZgU0,580445029.0,ACoAACKY42UB-5MF-Di8nhxzJnPKV5LPrdLZgU0,No,No,8.616573e+14,8/23/2025,8/23/2025,Untitled LinkedIn Profile Visitor (1),Untitled LinkedIn Profile Visitor (1)
2,https://linkedin.com/in/simran-chhabra-429626150,https://www.linkedin.com/sales/lead/ACoAACRmVO...,Simran Chhabra,Simran,Chhabra,Tech Prastish Software Solutions Pvt Ltd,NaN,Senior Software Engineer,Apr 2023 - Present,"Sahibzada Ajit Singh Nagar, Punjab, India · On...",...,ACoAACRmVOEBITTNt98C0lAfBK7l_9CnZs4qO4w,610686177.0,ACoAACRmVOEBITTNt98C0lAfBK7l_9CnZs4qO4w,No,Yes,9.093973e+14,8/23/2025,8/23/2025,Untitled LinkedIn Profile Visitor (1),Untitled LinkedIn Profile Visitor (1)
3,https://linkedin.com/in/mohit-khandelwal-972929a0,https://www.linkedin.com/sales/lead/ACoAABV-kC...,Mohit Khandelwal,Mohit,Khandelwal,Clover IT Services Pvt. Ltd.,NaN,Team Lead & Senior Software Developer.(Android...,Mar 2021 - Present,"Jaipur, Rajasthan, India",...,ACoAABV-kCYBxPwZH5xEOniUDtqOVSodwx7Ajt4,360615974.0,ACoAABV-kCYBxPwZH5xEOniUDtqOVSodwx7Ajt4,No,Yes,5.381593e+15,8/23/2025,8/23/2025,Untitled LinkedIn Profile Visitor (1),Untitled LinkedIn Profile Visitor (1)
4,https://linkedin.com/in/yesha-shah-52335a19b,https://www.linkedin.com/sales/lead/ACoAAC7cL2...,Yesha Shah,Yesha,Shah,Accenture,NaN,Application Development Analyst,Oct 2021 - Present,"Bangalore Urban, Karnataka, India",...,ACoAAC7cL2sBkqYFoDWVEqkxLJRCE-YLUPbP1MA,786181995.0,ACoAAC7cL2sBkqYFoDWVEqkxLJRCE-YLUPbP1MA,No,No,2.765136e+15,8/23/2025,8/23/2025,Untitled LinkedIn Profile Visitor (1),Untitled LinkedIn Profile Visitor (1)

In [11]:
df.describe()

,linkedinFollowersCount,linkedinSchoolCompanySlug,linkedinPreviousSchoolCompanySlug,linkedinProfileId,id
count,39.000000,3.400000e+01,1.400000e+01,4.900000e+01,4.900000e+01
mean,2556.564103,1.435359e+07,1.259916e+07,5.129716e+08,4.031537e+15
std,3077.896982,1.097178e+07,4.549583e+06,2.521514e+08,2.439849e+15
min,94.000000,3.781400e+05,3.757310e+05,6.694794e+07,1.444763e+14
25%,898.000000,1.334801e+07,1.020949e+07,3.388431e+08,2.087003e+15
50%,1497.000000,1.510765e+07,1.511610e+07,5.216782e+08,3.746909e+15
75%,2938.000000,1.511824e+07,1.511785e+07,6.324588e+08,6.080722e+15
max,13807.000000,6.945678e+07,1.512527e+07,1.240865e+09,8.496354e+15

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 48 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   linkedinProfileUrl                 61 non-null     object
 1   salesNavigatorProfileUrl           49 non-null     object
 2   fullName                           49 non-null     object
 3   firstName                          49 non-null     object
 4   lastName                           49 non-null     object
 5   companyName                        49 non-null     object
 6   personalWebsite                    6 non-null      object
 7   linkedinJobTitle                   49 non-null     object
 8   linkedinJobDateRange               49 non-null     object
 9   linkedinJobLocation                48 non-null     object
 10  linkedinHeadline                   49 non-null     object
 11  location                           49 non-null     object
 12  personalEmail1                     4 non-null      object
 13  website1                           6 non-null      object
 14  linkedinFollowersCount             39 non-null     float64
 15  linkedinOpenProfile                49 non-null     object
 16  linkedinDescription                44 non-null     object
 17  linkedinSkillsLabel                49 non-null     object
 18  previousCompanyName                49 non-null     object
 19  linkedinPreviousJobTitle           49 non-null     object
 20  linkedinPreviousJobDateRange       49 non-null     object
 21  linkedinPreviousJobLocation        47 non-null     object
 22  linkedinJobDescription             40 non-null     object
 23  linkedinPreviousJobDescription     46 non-null     object
 24  linkedinSchoolName                 47 non-null     object
 25  linkedinSchoolCompanyUrl           34 non-null     object
 26  linkedinSchoolCompanySlug          34 non-null     float64
 27  linkedinSchoolDegree               46 non-null     object
 28  linkedinSchoolDateRange            46 non-null     object
 29  linkedinSchoolDescription          13 non-null     object
 30  linkedinPreviousSchoolName         29 non-null     object
 31  linkedinPreviousSchoolCompanyUrl   14 non-null     object
 32  linkedinPreviousSchoolCompanySlug  14 non-null     float64
 33  linkedinPreviousSchoolDegree       26 non-null     object
 34  linkedinPreviousSchoolDateRange    27 non-null     object
 35  linkedinPreviousSchoolDescription  10 non-null     object
 36  linkedinMutualConnectionsUrl       49 non-null     object
 37  linkedinProfileSlug                49 non-null     object
 38  salesNavigatorProfileSlug          49 non-null     object
 39  linkedinProfileId                  49 non-null     float64
 40  linkedinProfileUrn                 49 non-null     object
 41  linkedinIsHiringBadge              49 non-null     object
 42  linkedinIsOpenToWorkBadge          49 non-null     object
 43  id                                 49 non-null     float64
 44  createdAt                          49 non-null     object
 45  updatedAt                          49 non-null     object
 46  createdBy                          49 non-null     object
 47  updatedBy                          49 non-null     object
dtypes: float64(5), object(43)
memory usage: 26.0+ KB

In [13]:
df.isnull().sum()

linkedinProfileUrl                    8
salesNavigatorProfileUrl             20
fullName                             20
firstName                            20
lastName                             20
companyName                          20
personalWebsite                      63
linkedinJobTitle                     20
linkedinJobDateRange                 20
linkedinJobLocation                  21
linkedinHeadline                     20
location                             20
personalEmail1                       65
website1                             63
linkedinFollowersCount               30
linkedinOpenProfile                  20
linkedinDescription                  25
linkedinSkillsLabel                  20
previousCompanyName                  20
linkedinPreviousJobTitle             20
linkedinPreviousJobDateRange         20
linkedinPreviousJobLocation          22
linkedinJobDescription               29
linkedinPreviousJobDescription       23
linkedinSchoolName                   22
linkedinSchoolCompanyUrl             35
linkedinSchoolCompanySlug            35
linkedinSchoolDegree                 23
linkedinSchoolDateRange              23
linkedinSchoolDescription            56
linkedinPreviousSchoolName           40
linkedinPreviousSchoolCompanyUrl     55
linkedinPreviousSchoolCompanySlug    55
linkedinPreviousSchoolDegree         43
linkedinPreviousSchoolDateRange      42
linkedinPreviousSchoolDescription    59
linkedinMutualConnectionsUrl         20
linkedinProfileSlug                  20
salesNavigatorProfileSlug            20
linkedinProfileId                    20
linkedinProfileUrn                   20
linkedinIsHiringBadge                20
linkedinIsOpenToWorkBadge            20
id                                   20
createdAt                            20
updatedAt                            20
createdBy                            20
updatedBy                            20
dtype: int64

In [15]:
df_copy = df.dropna(subset=['linkedinSkillsLabel'])

In [18]:
# Number of non-null values in 'skills' column
print("Count of non-null skills:", df['linkedinSkillsLabel'].count())

# Total number of rows in 'skills' column (including nulls)
print("Total rows in skills column:", len(df['linkedinSkillsLabel']))

Count of non-null skills: 49
Total rows in skills column: 69

In [19]:
# Drop rows where 'skills' column has null values
df = df.dropna(subset=['linkedinSkillsLabel'])

# Reset index after dropping
df = df.reset_index(drop=True)

print("Remaining rows after dropping nulls:", len(df))

Remaining rows after dropping nulls: 49

In [23]:
df.shape[1]

48

In [22]:
df.size

2352

In [25]:
df['linkedinSkillsLabel'].head(50)

0     REST APIs, Android SDK, Java, Push Notificatio...
1     Data Science, Deep Learning, Regression Analys...
2     State Managment( GetX, Provider), Flutter SDK,...
3     GraphQL, Model-view-viewmodel (MVVM), Database...
4     Application Architecture, Technical Requiremen...
5     Mobile Application Development, Android Studio...
6     Kotlin Coroutines, Navigation, MVVM, AVPlayer,...
7     Flutter, Getx, Dart, Retrofit, Dagger (Softwar...
8     Software Design, Proof of Concept, MVP, User E...
9     Clean Architecture, Emerging Mobile Technologi...
10    Leading Development Teams, User Experience (UX...
11    Agile Application Development, Android, Kotlin...
12    Kotlin, Android Development, Android, Core Jav...
13    Contract Negotiation, Channel Partners, Sales ...
14    SME development, Cross-functional Coordination...
15    MVP, Model-view-viewmodel (MVVM), REST APIs, A...
16    android java, Google Places, Geocoding, Core J...
17    Mobile Application Development, Start-up Leade...
18    Video Analytics, Video Playback, Agile Methodo...
19    Facebook API, Team Management, iOS, Design Pat...
20    SOLID Design Principles, Mobile Applications, ...
21    Computer Science, Design-Build, Performance Tu...
22    KMP, Mobile Applications, Android, MySQL, SQL,...
23    JSON, REST APIs, SQLite, Mobile Application De...
24    Git, SQL, RxJava, Application Programming Inte...
25    Barcode Technology, Zebra, RFID Applications, ...
26    Jetpack Compose, TensorFlow Lite, Bluetooth Lo...
27    Continuous Integration and Continuous Delivery...
28    Microsoft Office, Microsoft Excel, Microsoft W...
29    Android, Room Database, Mobile Application Dev...
30    Android, KMP, Flutter, Bloc, Data Store, Fireb...
31    Flutter, Android SDK, Android SDK,Kotlin , MVV...
32    Dart, Java, Android SDK, Mobile Application De...
33    nodejs, MySQL, Koa.js, TypeScript, React.js, D...
34    Twilio, GitHub, Room Database, Firebase crashl...
35    Jetpack compose, RxJava, XML, Corotines, Getx,...
36    Android Jetpack, Jaon, Kotlin, Git, Android St...
37    SwiftUI, Objective-C, Swift, SQLite, Core Data...
38    Mentoring, Modern Architecture, Agile Leadersh...
39    Corrective Actions, Pulse, Performance Improve...
40    Android Design, Mobile Applications, Coroutine...
41    BSI Compliance Manager, Git, Kotlin Coroutines...
42    Prompt Engineering, SQLite, Object-Oriented Pr...
43    CI, Dart, Business-to-Business (B2B), User Exp...
44    Kotlin, Databases, Order Management, X-Cart, C...
45    XML, Application Programming Interfaces (API),...
46    Kotlin Coroutines, In app purchase, Data Bindi...
47    Programming Languages, Code Review, Problem So...
48    Custom Widget, Collection, VCS, Bluetooth, Fir...
Name: linkedinSkillsLabel, dtype: object

In [26]:
# Define the columns you want to keep
required_columns = ["fullName", "linkedinProfileUrl", "linkedinSkillsLabel", "linkedinPreviousJobTitle", "linkedinPreviousJobDescription"]

In [27]:
# Keep only those columns (drop all others)
filtered_df = merged_df[required_columns]

In [28]:
filtered_df.head()

,fullName,linkedinProfileUrl,linkedinSkillsLabel,linkedinPreviousJobTitle,linkedinPreviousJobDescription
0,Shoaib Khan,https://linkedin.com/in/shoaib-khan-9b80b0205,"REST APIs, Android SDK, Java, Push Notificatio...",Senior Android Developer,I have an experience of 8+ years in Android Ap...
1,Arivazhahan Selva,https://linkedin.com/in/arivazhahan-selva-8314...,"Data Science, Deep Learning, Regression Analys...",Customer Excellence,Skills: Customer Success · Workload Prioritiza...
2,Simran Chhabra,https://linkedin.com/in/simran-chhabra-429626150,"State Managment( GetX, Provider), Flutter SDK,...",Flutter Developer,🔹 Cross-Platform Development: Built and mainta...
3,Mohit Khandelwal,https://linkedin.com/in/mohit-khandelwal-972929a0,"GraphQL, Model-view-viewmodel (MVVM), Database...",Senior Android Developer,Skills: Programming Languages · Android Develo...
4,Yesha Shah,https://linkedin.com/in/yesha-shah-52335a19b,"Application Architecture, Technical Requiremen...",Mobile Application Developer,Skills: Version Control · Google Material Desi...

In [35]:
filtered_df.shape

(69, 5)

In [34]:
filtered_df.isnull().sum()

fullName                          20
linkedinProfileUrl                 8
linkedinSkillsLabel               20
linkedinPreviousJobTitle          20
linkedinPreviousJobDescription    23
dtype: int64

In [37]:
# Drop rows where 'skills' column has null values
df_new = df_new.dropna(subset=['linkedinSkillsLabel'])

# Reset index after dropping
df_new = df_new.reset_index(drop=True)

print("Remaining rows after dropping nulls:", len(df_new))

Remaining rows after dropping nulls: 49

In [17]:
import pandas as pd
import re
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [18]:
def clean_skills(skill_str):
    if pd.isna(skill_str) or skill_str.strip() == "":
        return []
    skill_str = re.sub(r'[^a-zA-Z, ]', '', skill_str)  # remove special chars/numbers
    skills = [s.strip().lower() for s in skill_str.split(",") if s.strip() != ""]
    return skills

In [21]:
# Sample candidate data
candidates_data = pd.DataFrame(filtered_df)

candidates_data["linkedinSkillsLabel"] = candidates_data["linkedinSkillsLabel"].apply(clean_skills)

In [22]:
job_skills_required = {
  "must": [
    "python",
    "sql",
    "machine learning",
    "statistics",
    "pandas",
    "scikit-learn"
  ],
  "nice": [
    "numpy",
    "deep learning",
    "nlp",
    "transformers",
    "data structures",
    "algorithms",
    "git"
  ],
  "bonus": [
    "pytorch",
    "tensorflow",
    "mlops",
    "docker",
    "langchain",
    "aws",
    "gcp",
    "azure"
  ]
}

In [24]:
# Create skill vocabulary
all_skills = set()
for s in candidates_data["linkedinSkillsLabel"]:
    all_skills.update(s)
for k in job_skills_required.values():
    all_skills.update(k)

all_skills = sorted(list(all_skills))

In [25]:
# ---------------- Step 3: Create Vectors ----------------
def create_vector(skills, vocab, weights=None):
    vec = []
    for v in vocab:
        if v in skills:
            if weights and v in weights:
                vec.append(weights[v])
            else:
                vec.append(1)
        else:
            vec.append(0)
    return np.array(vec)

In [28]:
# Assign weights
weights = {}
for s in job_skills_required["must"]: weights[s] = 3
for s in job_skills_required["nice"]: weights[s] = 2
for s in job_skills_required["bonus"]: weights[s] = 1
    
job_vec = create_vector(all_skills, all_skills, weights)

In [31]:
# ---------------- Step 4: Score Candidates ----------------
results = []
for idx, row in candidates_data.iterrows():
    cand_vec = create_vector(row["linkedinSkillsLabel"], all_skills)
    
    # Cosine similarity
    sim = cosine_similarity([cand_vec], [job_vec])[0][0]
    
    # Missing skills
    missing = len(set(job_skills_required["must"] + 
                      job_skills_required["nice"] + 
                      job_skills_required["bonus"]) - set(row["linkedinSkillsLabel"]))
    
    score = max(0, 100 - (missing * 10))
    
    results.append([row["fullName"], row["linkedinSkillsLabel"], score, sim])

results_df = pd.DataFrame(results, columns=["fullName", "linkedinSkillsLabel", "Score", "CosineSim"])
results_df = results_df.sort_values(by="Score", ascending=False)

print(results_df)

          fullName                                linkedinSkillsLabel  Score  \
0      Shoaib Khan  [rest apis, android sdk, java, push notificati...      0
44    Surendra Pal  [twilio, github, room database, firebase crash...      0
50             NaN                                                 []      0
49             NaN                                                 []      0
48  Mohammad Hafiz  [mentoring, modern architecture, agile leaders...      0
..             ...                                                ...    ...
29    Roushan Arya  [git, sql, rxjava, application programming int...      0
30             NaN                                                 []      0
31             NaN                                                 []      0
32             NaN                                                 []      0
68             NaN                                                 []      0

    CosineSim
0    0.209801
44   0.217571
50   0.000000
49   0.000000
48   0.259815
..        ...
29   0.233112
30   0.000000
31   0.000000
32   0.000000
68   0.000000

[69 rows x 4 columns]

In [37]:
results_df.head(50)

,fullName,linkedinSkillsLabel,Score,CosineSim
0,Shoaib Khan,"[rest apis, android sdk, java, push notificati...",0,0.209801
44,Surendra Pal,"[twilio, github, room database, firebase crash...",0,0.217571
50,NaN,[],0,0.000000
49,NaN,[],0,0.000000
48,Mohammad Hafiz,"[mentoring, modern architecture, agile leaders...",0,0.259815
47,Abhishek Sharma,"[swiftui, objectivec, swift, sqlite, core data...",0,0.112066
46,Minakshi kamboj,"[android jetpack, jaon, kotlin, git, android s...",0,0.235441
45,Sanjeev Kumar,"[jetpack compose, rxjava, xml, corotines, getx...",0,0.227719
43,Kuldeep Shukla,"[nodejs, mysql, koajs, typescript, reactjs, da...",0,0.163683
35,Anil kr Maurya,"[barcode technology, zebra, rfid applications,...",0,0.271695
42,Prince Singh,"[dart, java, android sdk, mobile application d...",0,0.142857
41,Mohanapriya R,"[flutter, android sdk, android sdk, kotlin, mv...",0,0.148690
40,Aman Agarwal,"[android, kmp, flutter, bloc, data store, fire...",0,0.288969
39,Sriram D.,"[android, room database, mobile application de...",0,0.227719
38,PREM MOHAN RAM,"[microsoft office, microsoft excel, microsoft ...",0,0.118864
37,Sudip Mukherjee,[continuous integration and continuous deliver...,0,0.172973
51,NaN,[],0,0.000000
52,NaN,[],0,0.000000
53,NaN,[],0,0.000000
54,Harpal Singh Sohi,"[corrective actions, pulse, performance improv...",0,0.265789
55,Manoj Kumar Yadav,"[android design, mobile applications, coroutin...",0,0.271900
56,dilip patel,"[bsi compliance manager, git, kotlin coroutine...",0,0.267653
57,Mahek Thaker,"[prompt engineering, sqlite, objectoriented pr...",0,0.268792
58,Nitesh Kumar Singh,"[ci, dart, businesstobusiness bb, user experie...",0,0.271695
59,Prem Chand,"[kotlin, databases, order management, xcart, c...",0,0.241101
60,Anshul Nema,"[xml, application programming interfaces api, ...",0,0.291662
61,Jignyasa Tandel,"[kotlin coroutines, in app purchase, data bind...",0,0.137823
62,Bhavik Patel,"[programming languages, code review, problem s...",0,0.269382
63,Janki Shah,"[custom widget, collection, vcs, bluetooth, fi...",0,0.268792
64,NaN,[],0,0.000000
65,NaN,[],0,0.000000
66,NaN,[],0,0.000000
67,NaN,[],0,0.000000
36,Dhananjay Kumar Prajapati,"[jetpack compose, tensorflow lite, bluetooth l...",0,0.283190
34,NaN,[],0,0.000000
1,Arivazhahan Selva,"[data science, deep learning, regression analy...",0,0.275647
9,Anshul Garg,"[clean architecture, emerging mobile technolog...",0,0.269382
15,NaN,[],0,0.000000
14,DEBANJAN SARKAR,"[sme development, crossfunctional coordination...",0,0.217145
13,Bikash Ranjan Roy,"[contract negotiation, channel partners, sales...",0,0.202031
12,Payal Tak,"[kotlin, android development, android, core ja...",0,0.125294
11,Ravi Nada,"[agile application development, android, kotli...",0,0.253780
10,ROHIT PAWAR,"[leading development teams, user experience ux...",0,0.231031
8,Gopal Jee Gupta,"[software design, proof of concept, mvp, user ...",0,0.265857
33,NaN,[],0,0.000000
7,PULKIT SHARMA,"[flutter, getx, dart, retrofit, dagger softwar...",0,0.190885
6,Vipul Thakur,"[kotlin coroutines, navigation, mvvm, avplayer...",0,0.202031
5,Navneet Sharma,"[mobile application development, android studi...",0,0.158486
4,Yesha Shah,"[application architecture, technical requireme...",0,0.259889
3,Mohit Khandelwal,"[graphql, modelviewviewmodel mvvm, databases, ...",0,0.280738

In [35]:
df_score_profile = results_df[results_df["Score"] > 10].sort_values(by="Score", ascending=False)

In [36]:
df_score_profile.head()

Empty DataFrame
Columns: [fullName, linkedinSkillsLabel, Score, CosineSim]
Index: []

In [38]:
# Example job dataset
jobs = pd.DataFrame({
    'job_skills_required': [
        """C++, Python, SQL, Data Structures, Algorithms, OOP, Git, Linux, System Design
Python, Pandas, NumPy, Scikit-learn, TensorFlow, PyTorch, SQL, Data Visualization, Statistics, Machine Learning
Java, Spring Boot, REST APIs, Microservices, Docker, Kubernetes, AWS, GitHub, CI/CD
R, Python, SQL, PowerBI, Tableau, Machine Learning, Deep Learning, Data Cleaning, Feature Engineering
JavaScript, React, Node.js, TypeScript, HTML, CSS, REST APIs, MongoDB, Cloud Deployment
Excel, SQL, Python, Statistics, Probability, Data Wrangling, Matplotlib, Seaborn, Hypothesis Testing
Go, C++, Distributed Systems, Multithreading, Cloud Infrastructure, Kafka, Redis, API Development
Python, NLP, HuggingFace, Transformers, TensorFlow, PyTorch, Text Mining, Sentiment Analysis, Deep Learning
Python, R, SQL, Spark, Hadoop, Big Data, Data Warehousing, ETL, Machine Learning, Cloud (AWS/GCP)"""
    ]
})

In [39]:
jobs.head()

                                 job_skills_required
0  C++, Python, SQL, Data Structures, Algorithms,...

In [42]:
# 1. Data Cleaning

def clean_text(text):
    if pd.isnull(text):
        return ""
    text = text.lower()  # lowercase
    text = ''.join([c if c.isalpha() or c.isspace() else ' ' for c in text])  # remove special chars/numbers
    return text

df_new['linkedinSkillsLabel'] = df_new['linkedinSkillsLabel'].apply(clean_text)
jobs['job_skills_required'] = jobs['job_skills_required'].apply(clean_text)

In [44]:
df_new.head()

,fullName,linkedinProfileUrl,linkedinSkillsLabel,linkedinPreviousJobTitle,linkedinPreviousJobDescription
0,Shoaib Khan,https://linkedin.com/in/shoaib-khan-9b80b0205,rest apis android sdk java push notificatio...,Senior Android Developer,I have an experience of 8+ years in Android Ap...
1,Arivazhahan Selva,https://linkedin.com/in/arivazhahan-selva-8314...,data science deep learning regression analys...,Customer Excellence,Skills: Customer Success · Workload Prioritiza...
2,Simran Chhabra,https://linkedin.com/in/simran-chhabra-429626150,state managment getx provider flutter sdk ...,Flutter Developer,🔹 Cross-Platform Development: Built and mainta...
3,Mohit Khandelwal,https://linkedin.com/in/mohit-khandelwal-972929a0,graphql model view viewmodel mvvm database...,Senior Android Developer,Skills: Programming Languages · Android Develo...
4,Yesha Shah,https://linkedin.com/in/yesha-shah-52335a19b,application architecture technical requiremen...,Mobile Application Developer,Skills: Version Control · Google Material Desi...

In [46]:

# 2. TF-IDF Vectorization

vectorizer = TfidfVectorizer()

In [50]:
# Combine all text (candidates + job) so TF-IDF has same vocabulary
all_text = df_new['linkedinSkillsLabel'].tolist() + jobs['job_skills_required'].tolist()

tfidf_matrix = vectorizer.fit_transform(all_text)

In [57]:
# Split back into candidate vectors & job vectors
candidate_tfidf = tfidf_matrix[:len(df_new)]
job_tfidf = tfidf_matrix[len(df_new):]

In [71]:
print(candidate_tfidf)

  (0, 231)	0.1398995844375939
  (0, 488)	0.1027030402209189
  (0, 124)	0.1398995844375939
  (0, 22)	0.09793579924495778
  (0, 396)	0.21915926012825376
  (0, 26)	0.11998557742519932
  (0, 324)	0.08382187779611215
  (0, 336)	0.16308155348677203
  (0, 400)	0.17071604668733012
  (0, 337)	0.09793579924495778
  (0, 569)	0.11069375744319992
  (0, 568)	0.20053949318452793
  (0, 327)	0.20053949318452793
  (0, 271)	0.11069375744319992
  (0, 450)	0.12714162623935174
  (0, 110)	0.10026974659226397
  (0, 278)	0.06965214983182484
  (0, 138)	0.06184361153329964
  (0, 513)	0.2423412291774319
  (0, 314)	0.21915926012825376
  (0, 18)	0.17071604668733012
  (0, 114)	0.17071604668733012
  (0, 301)	0.21915926012825376
  (0, 341)	0.18995343313385976
  (0, 298)	0.2423412291774319
  :	:
  (48, 204)	0.09310198837544825
  (48, 25)	0.17858478746944143
  (48, 55)	0.13490271379462923
  (48, 525)	0.10852939240679722
  (48, 362)	0.13490271379462923
  (48, 127)	0.0821560710189652
  (48, 181)	0.0700393332849119
  (48, 246)	0.10003907929656033
  (48, 93)	0.10852939240679722
  (48, 409)	0.13035088959698288
  (48, 488)	0.20504400985629484
  (48, 124)	0.09310198837544825
  (48, 22)	0.06517544479849144
  (48, 324)	0.11156549926226637
  (48, 271)	0.07366575790872833
  (48, 278)	0.09270583140095374
  (48, 138)	0.12346919882319046
  (48, 203)	0.05578274963113319
  (48, 454)	0.0821560710189652
  (48, 501)	0.06224718031275031
  (48, 262)	0.04454073225906938
  (48, 467)	0.05130126295626727
  (48, 21)	0.2227036612953469
  (48, 23)	0.07366575790872833
  (48, 447)	0.06517544479849144

In [61]:
print(job_tfidf)

  (0, 199)	0.09001917030859943
  (0, 168)	0.09001917030859943
  (0, 576)	0.09001917030859943
  (0, 52)	0.09001917030859943
  (0, 218)	0.09001917030859943
  (0, 494)	0.09001917030859943
  (0, 475)	0.09001917030859943
  (0, 322)	0.09001917030859943
  (0, 539)	0.09001917030859943
  (0, 551)	0.09001917030859943
  (0, 232)	0.09001917030859943
  (0, 434)	0.09001917030859943
  (0, 274)	0.09001917030859943
  (0, 242)	0.09001917030859943
  (0, 142)	0.09001917030859943
  (0, 207)	0.09001917030859943
  (0, 234)	0.09001917030859943
  (0, 588)	0.09001917030859943
  (0, 404)	0.09001917030859943
  (0, 178)	0.09001917030859943
  (0, 84)	0.09001917030859943
  (0, 526)	0.09001917030859943
  (0, 398)	0.09001917030859943
  (0, 279)	0.09001917030859943
  (0, 143)	0.09001917030859943
  :	:
  (0, 136)	0.033226789046388434
  (0, 204)	0.051966578531998465
  (0, 525)	0.060577666405943205
  (0, 524)	0.06341354681297749
  (0, 170)	0.060577666405943205
  (0, 500)	0.22928457227307542
  (0, 421)	0.3634659984356592
  (0, 354)	0.0814080824346547
  (0, 42)	0.14111878945254167
  (0, 348)	0.0814080824346547
  (0, 422)	0.1628161648693094
  (0, 288)	0.0814080824346547
  (0, 465)	0.0814080824346547
  (0, 330)	0.07055939472627083
  (0, 16)	0.07055939472627083
  (0, 289)	0.35279697363135415
  (0, 132)	0.1628161648693094
  (0, 126)	0.25324341016381496
  (0, 231)	0.051966578531998465
  (0, 22)	0.03637886719261412
  (0, 138)	0.02297219758276857
  (0, 203)	0.03113616250328697
  (0, 262)	0.02486122478372366
  (0, 23)	0.08223578164722921
  (0, 447)	0.07275773438522824

In [62]:
# 3. Cosine Similarity

similarity_scores = cosine_similarity(candidate_tfidf, job_tfidf)

In [64]:
# 4: Add scores back to candidates

df_new['similarity_score'] = similarity_scores.flatten() * 100  # scale to percentage

In [67]:
# 5: Sort by score
candidates_sorted = df_new.sort_values(by='similarity_score', ascending=False)

In [68]:
print(candidates_sorted)

                     fullName  \
41                dilip patel
1           Arivazhahan Selva
20               Sujeet Kumar
33             Kuldeep Shukla
30               Aman Agarwal
23               Sumeet singh
24               Roushan Arya
26  Dhananjay Kumar Prajapati
3            Mohit Khandelwal
46            Jignyasa Tandel
25             Anil kr Maurya
29                  Sriram D.
4                  Yesha Shah
14            DEBANJAN SARKAR
17      SATISH KUMAR GARTHIMA
34               Surendra Pal
9                 Anshul Garg
22               Rajesh saini
45                Anshul Nema
47               Bhavik Patel
21            Mamta Budhawale
36            Minakshi kamboj
18              sheetal kumar
15                  Deepthi M
11                  Ravi Nada
48                 Janki Shah
31              Mohanapriya R
40          Manoj Kumar Yadav
16     Mohammad Kashif Ansari
8             Gopal Jee Gupta
43         Nitesh Kumar Singh
37            Abhishek Sharma
44                 Prem Chand
5              Navneet Sharma
7               PULKIT SHARMA
19               Shivaji Nath
35              Sanjeev Kumar
38             Mohammad Hafiz
42               Mahek Thaker
0                 Shoaib Khan
2              Simran Chhabra
10                ROHIT PAWAR
27            Sudip Mukherjee
28             PREM MOHAN RAM
6                Vipul Thakur
12                  Payal Tak
39          Harpal Singh Sohi
32               Prince Singh
13          Bikash Ranjan Roy

                                   linkedinProfileUrl  \
41       https://linkedin.com/in/dilip-patel-825b60a9
1   https://linkedin.com/in/arivazhahan-selva-8314...
20                 https://linkedin.com/in/sujeetbcet
33           https://linkedin.com/in/iamkuldeepshukla
30            https://linkedin.com/in/amanagarwal9303
23     https://linkedin.com/in/sumeet-singh-025b97157
24     https://linkedin.com/in/roushan-arya-53a504188
26  https://linkedin.com/in/dhananjay-kumar-prajap...
3   https://linkedin.com/in/mohit-khandelwal-972929a0
46  https://linkedin.com/in/jignyasa-tandel-5682b410a
25   https://linkedin.com/in/anil-kr-maurya-351a48283
29          https://linkedin.com/in/sriram-d-28a676bb
4        https://linkedin.com/in/yesha-shah-52335a19b
14   https://linkedin.com/in/debanjan-sarkar-1985-kol
17             https://linkedin.com/in/satish-kumar-g
34     https://linkedin.com/in/surendra-pal-022224146
9        https://linkedin.com/in/anshul-garg-8920b799
22      https://linkedin.com/in/rajesh-saini-b9091b54
45       https://linkedin.com/in/anshul-nema-22386256
47              https://linkedin.com/in/bhavikpokar23
21             https://linkedin.com/in/mamta-s-jadhav
36  https://linkedin.com/in/minakshi-kamboj-8732a1165
18     https://linkedin.com/in/sheetal-kumar-5b007967
15        https://linkedin.com/in/deepthi-m-563b18186
11        https://linkedin.com/in/ravi-nada-643090153
48               https://linkedin.com/in/janki-shah12
31              https://linkedin.com/in/mohanapriya-r
40          https://linkedin.com/in/manoj-kumar-yadav
16     https://linkedin.com/in/mohammad-kashif-ansari
8               https://linkedin.com/in/gopaljeegupta
43         https://linkedin.com/in/nitesh-singh-kumar
37   https://linkedin.com/in/abhishek-sharma-17779a57
44             https://linkedin.com/in/prem-chand-dev
5             https://linkedin.com/in/navneet93sharma
7     https://linkedin.com/in/pulkit-sharma-137861126
19      https://linkedin.com/in/shivajinathiosdev2610
35    https://linkedin.com/in/sanjeev-kumar-9b8687193
38           https://linkedin.com/in/mohammad-android
42                https://linkedin.com/in/mahekthaker
0       https://linkedin.com/in/shoaib-khan-9b80b0205
2    https://linkedin.com/in/simran-chhabra-429626150
10       https://linkedin.com/in/rohit-pawar-095381aa
27   https://linkedin.com/in/sudip-mukherjee-1a699035
28   https://linkedin.com/in/prem-mohan-ram-a24552139
6       https://linkedin.com/in/vipul-thakur-50141bbb
12         https://linkedin.com/in/payal-tak-b65453b7
39  https://linkedin.com/in/harpal-singh-sohi-4b30...
32     https://linkedin.com/in/prince-singh-58ab30110
13  https://linkedin.com/in/bikash-ranjan-roy-0275...

                                  linkedinSkillsLabel  \
41  bsi compliance manager  git  kotlin coroutines...
1   data science  deep learning  regression analys...
20  solid design principles  mobile applications  ...
33  nodejs  mysql  koa js  typescript  react js  d...
30  android  kmp  flutter  bloc  data store  fireb...
23  json  rest apis  sqlite  mobile application de...
24  git  sql  rxjava  application programming inte...
26  jetpack compose  tensorflow lite  bluetooth lo...
3   graphql  model view viewmodel  mvvm   database...
46  kotlin coroutines  in app purchase  data bindi...
25  barcode technology  zebra  rfid applications  ...
29  android  room database  mobile application dev...
4   application architecture  technical requiremen...
14  sme development  cross functional coordination...
17  mobile application development  start up leade...
34  twilio  github  room database  firebase crashl...
9   clean architecture  emerging mobile technologi...
22  kmp  mobile applications  android  mysql  sql ...
45  xml  application programming interfaces  api  ...
47  programming languages  code review  problem so...
21  computer science  design build  performance tu...
36  android jetpack  jaon  kotlin  git  android st...
18  video analytics  video playback  agile methodo...
15  mvp  model view viewmodel  mvvm   rest apis  a...
11  agile application development  android  kotlin...
48  custom widget  collection  vcs  bluetooth  fir...
31  flutter  android sdk  android sdk kotlin   mvv...
40  android design  mobile applications  coroutine...
16  android java  google places  geocoding  core j...
8   software design  proof of concept  mvp  user e...
43  ci  dart  business to business  b b   user exp...
37  swiftui  objective c  swift  sqlite  core data...
44  kotlin  databases  order management  x cart  c...
5   mobile application development  android studio...
7   flutter  getx  dart  retrofit  dagger  softwar...
19  facebook api  team management  ios  design pat...
35  jetpack compose  rxjava  xml  corotines  getx ...
38  mentoring  modern architecture  agile leadersh...
42  prompt engineering  sqlite  object oriented pr...
0   rest apis  android sdk  java  push notificatio...
2   state managment  getx  provider   flutter sdk ...
10  leading development teams  user experience  ux...
27  continuous integration and continuous delivery...
28  microsoft office  microsoft excel  microsoft w...
6   kotlin coroutines  navigation  mvvm  avplayer ...
12  kotlin  android development  android  core jav...
39  corrective actions  pulse  performance improve...
32  dart  java  android sdk  mobile application de...
13  contract negotiation  channel partners  sales ...

                           linkedinPreviousJobTitle  \
41                         Senior Software Engineer
1                               Customer Excellence
20                                   Technical Lead
33                      Associate Software Engineer
30                 Software Develpment Engineer- II
23                                Android Developer
24                                Software Engineer
26                            Sr. Software Engineer
3                          Senior Android Developer
46                                Android Developer
25                            Android App Developer
29                                Android Developer
4                      Mobile Application Developer
14                   Information Technology Analyst
17                                       Co-Founder
34  Android Developer at Lucida Hospitality Pvt Ltd
9                          Senior Software Engineer
22                                Flutter Developer
45                                Software Engineer
47                            Sr. Android Developer
21                                Android Developer
36                               Software Developer
18                                Android Developer
15                                          Trainee
11                         Senior Software Engineer
48                                Android Developer
31                                Software Engineer
40                          Senior Android Engineer
16                         Senior android developer
8                        Layoff/position eliminated
43                         Senior Software Engineer
37                                Sr. iOS Developer
44                            Application Developer
5                          Associate Staff Engineer
7                          Senior android developer
19                                    iOS Developer
35                                Android Developer
38                                Software Engineer
42                     Software Engineer -  Android
0                          Senior Android Developer
2                                 Flutter Developer
10                            Development Team Lead
27                                Android Developer
28                            Android app developer
6                             Sr. Android Developer
12                                Android Developer
39                  Human Resource Business Partner
32                                Android Developer
13                Sr Manager (Global Student Cards)

                       linkedinPreviousJobDescription  similarity_score
41  Worked on The FoodNetwork Kitchen owned by Dis...         26.433827
1   Skills: Customer Success · Workload Prioritiza...         21.305603
20  Led the development of PEPO and Ezkirana, stre...         15.824835
33  Skills: MongoDB · Express.js · Reactjs · Koa.j...         15.557734
30  - Guide junior developers through mentorship, ...         14.914897
23  Skills: Software Design · Databases · Data Str...         12.923983
24                                        Skills: SQL         12.578574
26                Skills: Model-view-viewmodel (MVVM)         10.129444
3   Skills: Programming Languages · Android Develo...          9.685863
46              Skills: Git · REST APIs · Android SDK          9.509236
25  Skills: Android SDK · GitHub · gson · Retrofit...          9.004850
29  Skills: Model-view-viewmodel (MVVM) · Android ...          8.788701
4   Skills: Version Control · Google Material Desi...          8.624137
14  •Trained and mentored junior developers and en...          8.439719
17  Driven by a deep passion for technology and en...          7.577085
34  Skills: Mobile Application Development · Fireb...          7.492038
9   In my role as a Senior Software Engineer at UK...          7.464477
22  Designed and developed app modules for restaur...          7.406095
45  Skills: Representational State Transfer (REST)...          7.221015
47                                Skills: Code Review          7.141239
21  Skills: Android Design · SOLID Design Principl...          7.132997
36  Skills: Java · Android Studio · Git · Android ...          7.131394
18  Skills: Object-Oriented Programming (OOP) · Fi...          6.802888
15                                  Android Developer          6.637853
11                                                NaN          6.441901
48  Enhanced an existing Java-based Android projec...          6.152588
31                                                NaN          5.814966
40  At NEO, we challenge conventional ways to unco...          5.809990
16  ● Developed a Sleep Aid module that streams ca...          5.723464
8   >> Completed contractual cost-cutting project ...          5.448000
43  Technology: Android studio, SonarQube, NPM, GI...          5.320635
37  Work with iOT Technology, Communication with B...          5.316964
44  Internal Employee App (Kotlin, MVVM, Room, Vol...          5.251223
5                 Skills: Kotlin · Android SDK · Java          4.931802
7   As a senior Android developer, my role and res...          4.366576
19  Skills: UIKit · REST APIs · JSON · Git · Faceb...          4.267536
35  Skills: Git · Android · Java · Andriod App Dev...          4.257621
38  Technology development firm focused on softwar...          4.069729
42  Skills: Android Studio · Android Design · RxJa...          4.003071
0   I have an experience of 8+ years in Android Ap...          3.441992
2   🔹 Cross-Platform Development: Built and mainta...          2.934944
10  Skills: Mobile Application Development · Leadi...          2.684123
27  Skills: Code Review · Xamarin Forms · xamarin ...          2.642895
28                         Native app ! java l Kotlin          1.715205
6   ● Developed scalable features using MVVM archi...          1.370781
12                                                NaN          1.103033
39  In my role at Myntra, I partnered with busines...          0.964892
32  Skills: Mobile Application Development · Flutt...          0.832755
13  Key Accounts Management/Strategic Partnership ...          0.174906

In [70]:
candidates_sorted.head()

,fullName,linkedinProfileUrl,linkedinSkillsLabel,linkedinPreviousJobTitle,linkedinPreviousJobDescription,similarity_score
41,dilip patel,https://linkedin.com/in/dilip-patel-825b60a9,bsi compliance manager git kotlin coroutines...,Senior Software Engineer,Worked on The FoodNetwork Kitchen owned by Dis...,26.433827
1,Arivazhahan Selva,https://linkedin.com/in/arivazhahan-selva-8314...,data science deep learning regression analys...,Customer Excellence,Skills: Customer Success · Workload Prioritiza...,21.305603
20,Sujeet Kumar,https://linkedin.com/in/sujeetbcet,solid design principles mobile applications ...,Technical Lead,"Led the development of PEPO and Ezkirana, stre...",15.824835
33,Kuldeep Shukla,https://linkedin.com/in/iamkuldeepshukla,nodejs mysql koa js typescript react js d...,Associate Software Engineer,Skills: MongoDB · Express.js · Reactjs · Koa.j...,15.557734
30,Aman Agarwal,https://linkedin.com/in/amanagarwal9303,android kmp flutter bloc data store fireb...,Software Develpment Engineer- II,"- Guide junior developers through mentorship, ...",14.914897